version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --root-path /bot --port ${PORT}
    ports:
      - "${PORT}:${PORT}"