version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --loop uvloop
    ports:
      - "${PORT}:${PORT}"
    networks:
      - npm
      - telegram

networks:
  npm:
    external: true
    name: npm
  telegram:
    driver: bridge

