[tool.poetry]
name = "dude-duck-frontend"
version = "0.1.0"
description = ""
authors = ["CraazzzyyFoxx <craazzzyyfoxx@gmail.com>"]
readme = "README.md"
packages = [{include = "dude_duck_frontend"}]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.0"
pydantic = {extras = ["email"], version = "^2.1.1"}
python-dotenv = "^1.0.0"
loguru = "^0.7.0"
sentry-sdk = {extras = ["fastapi"], version = "^1.28.1"}
fastapi = "^0.100.0"
uvloop = {version = "^0.17.0", platform="linux"}
pydantic-settings = "^2.0.2"
aiogram = {version = "^3.0.0b9", allow-prereleases = true}
aiogram-dialog = {version = "^2.0.0b21", allow-prereleases = true}
beanie = "^1.21.0"
httpx = "^0.24.1"
orjson = "^3.9.4"
babel = "^2.12.1"
pydantic-extra-types = "^2.0.0"
phonenumbers = "^8.13.18"
dateparser = "^1.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
